#!/usr/bin/env node
/* =========================================================================
   build-sandbox.js — regenerate /sandbox/ from the live game.

     node tools/build-sandbox.js

   The sandbox is a full copy of the game at crowdsense.uk/sandbox/ where a
   change can be tried out before it goes near the real thing. app.js and
   questions.js are copied verbatim, so the sandbox runs the same engine that
   players run; only index.html is rewritten, to isolate it:

     - localStorage is shimmed to prefix every key, so sandbox play cannot
       read or write a real player's stats, streak or saved games. The game
       refuses to load if that shim does not take effect.
     - the crowd API is switched off, so sandbox guesses never reach the
       real "closer than X% of players" data
     - analytics, the service worker and the web manifest are stripped
     - noindex, and a banner across the top, so it can never be mistaken
       for the live game
     - ?day=YYYY-MM-DD previews any day's question, including future ones

   Workflow: run this to reset the sandbox to match live, make the candidate
   edit inside sandbox/, test it, then apply the same edit to the root files
   and run this again. Every rewrite below fails loudly if what it expects
   is missing, so this can never silently emit a half-isolated sandbox.
   ========================================================================= */

var fs = require("fs");
var path = require("path");

var ROOT = path.join(__dirname, "..");
var OUT = path.join(ROOT, "sandbox");
var PREFIX = "sbx:";

// SANDBOX TRIAL: two guesses with points, a monthly leaderboard on dummy
// data, and a signup mock. Its files live in tools/sandbox-trial/ and are
// layered on top of the live engine — app.js is still copied untouched, and
// trial.js swaps in the few functions the trial changes. Set to false to
// build a plain copy of live again.
var TRIAL = true;
var TRIAL_DIR = path.join(__dirname, "sandbox-trial");

function read(f){ return fs.readFileSync(path.join(ROOT, f), "utf8"); }
function write(f, s){ fs.writeFileSync(path.join(OUT, f), s); }

// Every transform goes through this, so a rewrite that no longer matches
// stops the build instead of shipping an unisolated sandbox.
function replaceOnce(src, find, repl, what){
  var parts = src.split(find);
  if (parts.length !== 2){
    throw new Error("build-sandbox: expected exactly one match for " + what +
      " in index.html, found " + (parts.length - 1) + ". Update tools/build-sandbox.js.");
  }
  return parts[0] + repl + parts[1];
}

if (!fs.existsSync(OUT)) fs.mkdirSync(OUT);

/* ---------- the engine and the bank, copied as-is ---------- */
write("app.js", read("app.js"));
write("questions.js", read("questions.js"));

/* ---------- index.html, rewritten ---------- */
var html = read("index.html");

// 1. title
html = replaceOnce(html,
  "<title>Crowdsense — how well do you know the British public?</title>",
  "<title>Crowdsense SANDBOX — not the live game</title>",
  "the page title");

// 2. keep it out of search results, and install the storage shim before
//    anything else can touch localStorage
var head = [
  '<meta name="robots" content="noindex, nofollow" />',
  '  <script>',
  '  /* Sandbox storage isolation. Every key the game reads or writes is',
  '     transparently prefixed, and enumeration only sees prefixed keys, so',
  '     the real cs-stats / streakCount / cs-state-* records are untouchable',
  '     from here. Generated by tools/build-sandbox.js — do not hand-edit. */',
  '  (function(){',
  '    var P = ' + JSON.stringify(PREFIX) + ';',
  '    var real = null;',
  '    try{ real = window.localStorage; }catch(_){ return; }',
  '    if (!real) return;',
  '    function ownKeys(){',
  '      var out = [];',
  '      for (var i = 0; i < real.length; i++){',
  '        var k = real.key(i);',
  '        if (k && k.indexOf(P) === 0) out.push(k.slice(P.length));',
  '      }',
  '      return out;',
  '    }',
  '    var shim = {',
  '      getItem: function(k){ return real.getItem(P + k); },',
  '      setItem: function(k, v){ real.setItem(P + k, v); },',
  '      removeItem: function(k){ real.removeItem(P + k); },',
  '      clear: function(){ ownKeys().forEach(function(k){ real.removeItem(P + k); }); },',
  '      key: function(i){ var ks = ownKeys(); return (i >= 0 && i < ks.length) ? ks[i] : null; },',
  '      get length(){ return ownKeys().length; }',
  '    };',
  '    try{',
  '      Object.defineProperty(window, "localStorage", {',
  '        configurable: true, get: function(){ return shim; }',
  '      });',
  '    }catch(_){ return; }',
  '    // Prove it took: a write through the shim must land on the prefixed',
  '    // key and nowhere else. Only then is the game allowed to load.',
  '    try{',
  '      var probe = "__sbx_probe__";',
  '      window.localStorage.setItem(probe, "1");',
  '      var ok = real.getItem(P + probe) === "1" && real.getItem(probe) === null;',
  '      window.localStorage.removeItem(probe);',
  '      window.__SBX_ISOLATED = ok && real.getItem(P + probe) === null;',
  '    }catch(_){ window.__SBX_ISOLATED = false; }',
  '  })();',
  '  </script>',
  '  <script>',
  '  /* Sandbox reset: wipe only the sandbox\'s own keys. */',
  '  function sbxReset(){',
  '    try{ window.localStorage.clear(); }catch(_){}',
  '    location.reload();',
  '  }',
  '  </script>'
].join("\n  ");
html = replaceOnce(html, '<meta name="viewport" content="width=device-width, initial-scale=1" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1" />\n  ' + head,
  "the viewport meta tag");

// 3. no manifest, no apple icon — nothing that invites installing this to a
//    home screen alongside the real game
html = replaceOnce(html, '<link rel="manifest" href="manifest.webmanifest" />',
  '<!-- manifest removed in the sandbox -->', "the manifest link");
html = replaceOnce(html, '<link rel="apple-touch-icon" href="apple-touch-icon.png" />',
  '<!-- apple-touch-icon removed in the sandbox -->', "the apple-touch-icon link");

// 4. crowd layer off, and TODAY driven by ?day=
var cfg = [
  'window.CS_CONFIG = Object.assign({',
  '      ANCHOR: "2026-07-20",',
  '      SITE_URL: "https://crowdsense.uk/sandbox/",',
  '      // Crowd layer deliberately off: sandbox guesses must never land in',
  '      // the real distribution behind "closer than X% of players".',
  '      CROWD_API_URL: "",',
  '      // ?day=YYYY-MM-DD previews any day, including ones not yet reached.',
  '      TODAY: (function(){',
  '        var m = /[?&]day=(\\d{4}-\\d{2}-\\d{2})/.exec(location.search);',
  '        return m ? m[1] : "";',
  '      })()' + (TRIAL ? ',' : ''),
].concat(TRIAL ? [
  '      // SANDBOX TRIAL: two guesses; only an exact first guess skips the second',
  '      MAX_GUESSES: 2,',
  '      BULLSEYE: 0'
] : []).concat([
  '    }, window.CS_CONFIG || {});'
]).join("\n      ");
var liveCfg = html.match(/window\.CS_CONFIG = Object\.assign\(\{[\s\S]*?\}, window\.CS_CONFIG \|\| \{\}\);/);
if (!liveCfg) throw new Error("build-sandbox: could not find the CS_CONFIG block in index.html.");
html = replaceOnce(html, liveCfg[0], cfg, "the CS_CONFIG block");

// 5. the game scripts load only once isolation is proven
var scripts = html.match(/<script src="questions\.js\?v=\d+"><\/script>\s*<script src="app\.js\?v=\d+"><\/script>/);
if (!scripts) throw new Error("build-sandbox: could not find the questions.js/app.js script tags in index.html.");
var loader = [
  '<script>',
  '    // Never load the game unless the storage shim is provably in place.',
  '    if (window.__SBX_ISOLATED){',
  '      ' + JSON.stringify(["questions.js", "app.js"].concat(TRIAL ? ["points.js", "menu.js", "trial.js"] : [])) + '.forEach(function(src){',
  '        var s = document.createElement("script");',
  '        s.src = src + "?sbx=" + Date.now();',
  '        s.async = false;',
  '        document.body.appendChild(s);',
  '      });',
  '    } else {',
  '      document.getElementById("sbxBlocked").hidden = false;',
  '      var app = document.querySelector(".app");',
  '      if (app) app.hidden = true;',
  '    }',
  '  </script>'
].join("\n  ");
html = replaceOnce(html, scripts[0], loader, "the game script tags");

// 6. no service worker: the sandbox should never cache or claim clients
var sw = html.match(/<script>\s*if \("serviceWorker" in navigator\)\{[\s\S]*?<\/script>/);
if (!sw) throw new Error("build-sandbox: could not find the service worker registration in index.html.");
html = replaceOnce(html, sw[0], "<!-- service worker not registered in the sandbox -->",
  "the service worker registration");

// 7. no analytics: sandbox visits must not show up in the real counts
var gc = html.match(/<!-- Analytics[\s\S]*?<\/script>/);
if (!gc) throw new Error("build-sandbox: could not find the analytics snippet in index.html.");
html = replaceOnce(html, gc[0], "<!-- analytics not loaded in the sandbox -->", "the analytics snippet");

// 8. an unmissable banner, plus the blocked-state message
var banner = [
  '<div class="sbx-bar">',
  '    SANDBOX — test copy, not the live game.',
  '    <button type="button" class="sbx-reset" onclick="sbxReset()">Reset this sandbox</button>',
  '  </div>',
  '  <div id="sbxBlocked" class="sbx-blocked" hidden>',
  '    <b>Sandbox stopped before loading.</b> This browser would not let the sandbox',
  '    separate its saved data from the real game\'s, so the game was not started —',
  '    your stats and streak are untouched. Try a different browser, or play the',
  '    real game at <a href="../">crowdsense.uk</a>.',
  '  </div>',
  '  <style>',
  '    .sbx-bar{',
  '      position:sticky; top:0; z-index:80; width:100%;',
  '      background:#121212; color:#fff; text-align:center;',
  '      font-size:12px; letter-spacing:.08em; text-transform:uppercase;',
  '      padding:8px 12px; display:flex; gap:12px; align-items:center; justify-content:center;',
  '      flex-wrap:wrap;',
  '    }',
  '    .sbx-reset{',
  '      font-family:inherit; font-size:11px; letter-spacing:.06em; text-transform:uppercase;',
  '      background:transparent; color:#fff; border:1px solid rgba(255,255,255,.5);',
  '      border-radius:4px; padding:3px 8px; cursor:pointer;',
  '    }',
  '    .sbx-blocked{',
  '      width:min(560px,94vw); margin:24px auto; padding:16px 18px;',
  '      border:1px solid #d5541a; border-radius:6px;',
  '      font-size:14px; line-height:1.6;',
  '    }',
  '  </style>'
].join("\n  ");
html = replaceOnce(html, "<body>", "<body>\n  " + banner, "the opening body tag");

// 9. SANDBOX TRIAL: its stylesheet, its scripts, and the leaderboard page,
//    which gets the same storage shim as the game so it only ever reads the
//    sandbox's own saved data
var trialFiles = ["points.js", "menu.js", "trial.js", "trial.css", "leaderboard.js"];
if (TRIAL){
  // the stylesheet's address carries a hash of its content: the scripts load
  // fresh every time, and a cached old stylesheet under new scripts leaves
  // their new elements unstyled
  var cssHash = require("crypto").createHash("sha1")
    .update(fs.readFileSync(path.join(TRIAL_DIR, "trial.css"))).digest("hex").slice(0, 10);
  html = replaceOnce(html, "</head>", '  <link rel="stylesheet" href="trial.css?v=' + cssHash + '" />\n</head>', "the closing head tag");
  trialFiles.forEach(function(f){
    fs.writeFileSync(path.join(OUT, f), fs.readFileSync(path.join(TRIAL_DIR, f), "utf8"));
  });
  var lb = fs.readFileSync(path.join(TRIAL_DIR, "leaderboard.html"), "utf8");
  lb = replaceOnce(lb, "<!--SBX-HEAD-->", head, "the leaderboard's head placeholder");
  write("leaderboard.html", lb);
} else {
  trialFiles.concat(["leaderboard.html"]).forEach(function(f){
    try{ fs.unlinkSync(path.join(OUT, f)); }catch(_){}
  });
}

write("index.html", html);

console.log("sandbox/ rebuilt from live:");
["index.html", "app.js", "questions.js"].concat(TRIAL ? trialFiles.concat(["leaderboard.html"]) : []).forEach(function(f){
  console.log("  " + f + "  " + fs.statSync(path.join(OUT, f)).size + " bytes");
});
console.log("open  https://crowdsense.uk/sandbox/            (today)");
console.log("      https://crowdsense.uk/sandbox/?day=2026-08-16   (a chosen day)");
if (TRIAL) console.log("      https://crowdsense.uk/sandbox/leaderboard.html   (the trial's leaderboard)");
